### ISSUE TITLE
Error encountered when running test.py

### ISSUE THREAD

**Issue by Lanxin1011** [Cameltr/RGTSI#5]
hello~ I have just downloaded the checkpoint files and prepared the structure data under your guidance. And I would like to test the model on my own data. However, when I was running test.py, an error occurred indicating that there is a size mismatch when loading the net_RefEN.pth.

The error message is as follows:

```initialize network with normal
initialize network with normal
initialize network with normal
/home/zlx/RGTSI/models/networks.py:60: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, 1.0, gain)
/home/zlx/RGTSI/models/networks.py:61: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  init.constant(m.bias.data, 0.0)
model [training1] was created
Traceback (most recent call last):
  File "test.py", line 43, in <module>
    model.netRefEN.module.load_state_dict(net_EN['net'])
  File "/home/zlx/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RefEncoder:
        size mismatch for Encoder_1.model.0.weight: copying a param with shape torch.Size([64, 6, 4, 4]) from checkpoint, the shape in current model is torch.Size([64, 3, 4, 4]).```

Please help me solve this problem, since I'm looking forward to the inpainting results. 

Best regards~

**Comment by Lanxin1011** [comment]
hello~ I've solved the problem by correcting a typo in test.py

In line 43, replace the original ```model.netRefEN.module.load_state_dict(net_EN['net'])``` with ```model.netRefEN.module.load_state_dict(net_RefEN['net'])``` can remove this error.

**Comment by Cameltr** [comment]
Thanks for pointing out this bug! I have corrected it.
